version: 2.1

aliases:
    - &dir ~/repo
    - &cache_key dependency-cache-{{ checksum "package.json" }}
    - &attach_workspace
      attach_workspace:
          at: *dir

executors:
    default:
        working_directory: *dir
        docker:
            - image: circleci/node:12

jobs:
    checkout_code:
        executor: default
        steps:
            - checkout
            - restore_cache:
                  key: *cache_key
            - run: npm install
            - save_cache:
                  key: *cache_key
                  paths:
                      - ./node_modules
            - persist_to_workspace:
                  root: *dir
                  paths:
                      - .

    test:
        executor: default
        steps:
            - *attach_workspace
            - run: npm run lint
            - run: npm test

    release:
        executor: default
        steps:
            - *attach_workspace
            - checkout # needed to set auth to allow pushing tag to git repo
            - run: npm run semantic-release

workflows:
    build:
        jobs:
            - checkout_code
            - test:
                  requires:
                      - checkout_code
            - release:
                  context: org-global
                  requires:
                      - test
                  filters:
                      branches:
                          only:
                              - master
